### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by idkjs** [jacobp100/technicalc-core#1]
This is tight work, boss. Thanks for sharing.

**Comment by jacobp100** [comment]
Thanks!

I'll do an update for this - but as a quick fix, I think you can just make a `dist` directory at the project root then try running again

**Comment by idkjs** [comment]
That, indeed, gets it built. Will have to keep that silly fix in mind. Assuming its supposed to run in the browser, will have to add an index.html somewhere too.

Thanks twice.

**Comment by idkjs** [comment]
Is this part of the project intended to be run outside of the app? As a cli or in the web maybe?

`npx parcel server dist/client.js` does not seem to think so. 

Thanks.

**Comment by jacobp100** [comment]
Ah, no, it doesn't work in the browser as-is. The only editor for the project is in the TechniCalc app, which is done in React Native, and apart from what is here, is closed source.

It should be relatively easy to make a basic editor in the browser with `client.js` and MathJax - `Elements.toMml` can be passed directly to MathJax to render in the page.

You can see an example of using the client on my website here:- https://github.com/jacobp100/jacob-does-code/blob/master/assets/technicalc/computation.js

To run this page, you'll need to have an encoded calculation which you can get from the app or the `Encoding` module from `technicalc-editor` - but an example https://jacobdoescode.com/technicalc?exdaF

**Comment by idkjs** [comment]
Thanks. I will study it. There is so much to learn here.
